#Makefile de los 8 laboratorios de Posix

GCC = gcc
FLAGS =
MODULO =

PROGRAMAS = lab01 lab02 lab03 lab04 lab05 lab06 lab07 lab08

lab01:
	$(GCC) $@.c -o $@

lab02:
	$(GCC) $@.c -o $@

lab03:
	$(GCC) $@.c -o $@

lab04:
	$(GCC) $@.c -o $@

lab05:
	$(GCC) $@.c -o $@

lab06:
	$(GCC) $@.c -o $@

lab07:
	$(GCC) $@.c -o $@

lab08:
	$(GCC) $@.c -o $@

clean:
	$(RM) $(PROGRAMAS)
