#Makefile utiizado para la ejecucion de los laboratorios de OpenMP
#Autor: Juan Diego Rojas


GCC = gcc
FLAGS = -lm -fopenmp

PROGRAMAS = lab01 lab02 lab03 lab04 lab05 lab06

lab01:
			$(GCC) $@.c -o $@ $(FLAGS)

lab02:
			$(GCC) $@.c -o $@ $(FLAGS)

lab03:
			$(GCC) $@.c -o $@ $(FLAGS)

lab04:
			$(GCC) $@.c -o $@ $(FLAGS)

lab05:
			$(GCC) $@.c -o $@ $(FLAGS)

lab06:
			$(GCC) $@.c -o $@ $(FLAGS)

clean:
			$(RM) $(PROGRAMAS) 
