#Makefile usado para la automatizacion en la compilacion del laboratorio de sistema de ficheros#

GCC = gcc
PROGRAMAS = lab01 lab02 lab03

lab01: 
			$(GCC) $@.c -o $@

lab02: 
			$(GCC) $@.c -o $@

lab03: 
			$(GCC) $@.c -o $@

clean:
			$(RM) $(PROGRAMAS)